// peekr-ui/src/components/ControlStick.tsx
import React from "react";
import { Box } from "@chakra-ui/react";

const backdropSize = 80;
const stickSize = 56;
const stickMotionFactor = 0.25;

export const ControlStick = ({ x, y }: { x: number; y: number }) => {
  const stickCenterOffset = (backdropSize - stickSize) / 2;
  const stickOffsets = [
    stickCenterOffset + x * backdropSize * stickMotionFactor,
    stickCenterOffset + y * backdropSize * stickMotionFactor,
  ];

  return (
    <Box
      w={`${backdropSize}px`}
      h={`${backdropSize}px`}
      borderRadius="100%"
      bgColor="gray.700"
      m={1}
    >
      <Box
        w={`${stickSize}px`}
        h={`${stickSize}px`}
        position="relative"
        left={`${stickOffsets[0]}px`}
        top={`${stickOffsets[1]}px`}
        borderRadius="100%"
        bgColor="gray.500"
      />
    </Box>
  );
};

// peekr-ui/src/components/ControlStick.svelte
<script lang="ts">
  export let x: number;
  export let y: number;

  const backdropSize = 80;
  const stickSize = 56;
  const stickMotionFactor = 0.25;

  const stickCenterOffset = (backdropSize - stickSize) / 2;

  $: stickOffsets = [
    stickCenterOffset + x * backdropSize * stickMotionFactor,
    stickCenterOffset + y * backdropSize * stickMotionFactor,
  ];
</script>

<div
  class="bg-gray-700 m-1 rounded-full"
  style={`width:${backdropSize}px;height:${backdropSize}px`}
>
  <div
    class="bg-gray-500 relative rounded-full will-change-transform"
    style={`width:${stickSize}px;\
      height:${stickSize}px;\
      transform:translate(${stickOffsets[0]}px,${stickOffsets[1]}px)`}
  />
</div>
